ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import home_page, about_page, contact_page, login_page, register_page,logout_request,forget_password,send_email_done,change_password,change_password_done
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_page, name='login'),
    path('about-us', about_page),
    path('contact-us', contact_page),
    path('register', register_page, name='register'),
    path('logout/', logout_request, name='logout'),
    path('templates/', include("products.urls")),
    path('forget-password/',forget_password),
    path('forget-password/send-email-sucessfull/',send_email_done,name='send-email-sucessfull'),
    path('change-password/',change_password,name='change_password'),
    path('change-password/change-password-sucessfull/',change_password_done,name='change-password-sucessfull'),
    
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views

app_name = 'products' 
urlpatterns = [
    path('', views.TemplateListView.as_view(), name='template'),
    path('setting/', views.setting_page, name='setting'),
    path('show/<str:username>/', views.show_template, name='show'),
    path('activate_tempalte/<str:temp_name>/', views.activate_template, name='activate_tempalte'),

]

templates/temps/temp_type_one.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title> Theme 1 </title>
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i|Playfair+Display:400,400i,700,700i,900,900i"
        rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="{% static  'temp_type_one/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Libraries CSS Files -->
    <link href="{% static  'temp_type_one/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <!-- Main Stylesheet File -->
    <link href="{% static  'temp_type_one/css/style.css' %}" rel="stylesheet">
    <!-- Responsive css -->
    <link href="{% static  'temp_type_one/css/responsive.css' %}" rel="stylesheet">
</head>

<body>
    <!-- start section header -->
    <div id="header" style="
    {% if object.head_image %}
        background-image: url( {{ object.head_image.url }} );
    {% else %}
        background-image: url( {% static 'temp_type_one/images/home-bg.jpg' %} );
    {% endif %}
  " class="home">

        <div class="container">
            <div class="header-content">
                <h1>
                    {% if object.title %}
                    {{ object.title }}
                    {% else %}
                    من وحید هستم
                    {% endif %}
                </h1>
                <p>
                    {% if object.sub_title %}
                        {{ object.sub_title }}
                    {% else %}
                        designer, developer
                    {% endif %}
                </p>
                <ul class="list-unstyled list-social">
                    {% if object.facebook_link %}
                    <li><a href="{{ object.facebook_link }}"><i class="ion-social-facebook"></i></a></li>
                    {% endif %}
                    {% if object.twitter_link %}
                    <li><a href="{{ object.twitter_link }}"><i class="ion-social-twitter"></i></a></li>
                    {% endif %}
                    {% if object.insta_link %}
                    <li><a href="{{ object.insta_link }}"><i class="ion-social-instagram"></i></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <!-- End section header -->


    <!-- start section about us -->
    <div id="about" class="paddsection">
        <div class="container">
            <div class="row justify-content-between">

                <div class="col-lg-4 ">
                    <div class="div-img-bg">
                        <div class="about-img">
                            <img src="
                            {% if object.description_image %}
                                {{ object.description_image.url }}
                            {% else %}
                                {% static 'temp_type_one/images/me.jpg' %}
                            {% endif %}
                            " class="img-responsive" alt="me">
                        </div>
                    </div>
                </div>

                <div class="col-lg-7">
                    <div class="about-descr">

                        <p class="p-heading text-right">
                            {% if object.description_title %}
                            {{ object.description_title }}
                            {% else %}
                            سلام اینجا تهران است
                            {% endif %}
                        </p>
                        <p class=" text-right">
                            {% if object.description_detail %}
                                {{ object.description_detail }}
                            {% else %}
                                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با است
                                فاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچ
                                نان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف
                                بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آین
                                ده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را
                                برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایج
                                اد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها
                                ، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی،
                                و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
                            {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- end section about us -->
</body>

</html>

templates/temps/temp_type_two.html
{% load static %}

<!DOCTYPE html>
<html>
<link type="text/css" rel="stylesheet" id="dark-mode-custom-link">
<link type="text/css" rel="stylesheet" id="dark-mode-general-link">
<style lang="en" type="text/css" id="dark-mode-custom-style"></style>
<style lang="en" type="text/css" id="dark-mode-native-style"></style>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'temp_type_two/w3.css' %}">
    <link rel="stylesheet" href="{% static 'temp_type_two/css.css' %}">
    <link rel="stylesheet" href="{% static 'temp_type_two/font-awesome.min.css' %}">
    <style>
        body,
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: "Montserrat", sans-serif
        }

        .w3-row-padding img {
            margin-bottom: 12px
        }

        /* Set the width of the sidebar to 120px */
        .w3-sidebar {
            width: 120px;
            background: #222;
        }

        /* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
        #main {
            margin-left: 120px
        }

        /* Remove margins from "page content" on small screens */
        @media only screen and (max-width: 600px) {
            #main {
                margin-left: 0
            }
        }
    </style>
</head>

<body class="w3-black">

    <!-- Icon Bar (Sidebar - hidden on small screens) -->
    <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
        <!-- Avatar image in top left corner -->
        <img src="
        {% if object.head_image %}
            {{ object.head_image.url }}
        {% else %}
            {% static 'temp_type_two/avatar_smoke.jpg' %}
        {% endif %}
        " style="width:100%">
        <a href="#" class="w3-bar-item w3-button w3-padding-large w3-black">
            <i class="fa fa-home w3-xxlarge"></i>
            <p>خانه</p>
        </a>
        <a href="#about" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
            <i class="fa fa-user w3-xxlarge"></i>
            <p>درباره من</p>
        </a>
        <a href="#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
            <i class="fa fa-eye w3-xxlarge"></i>
            <p>غکس ها</p>
        </a>
    </nav>

    <!-- Navbar on small screens (Hidden on medium and large screens) -->
    <div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
        <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
            <a href="#" class="w3-bar-item w3-button" style="width:25% !important">خانه</a>
            <a href="#about" class="w3-bar-item w3-button" style="width:25% !important">درباره من</a>
            <a href="#photos" class="w3-bar-item w3-button" style="width:25% !important">عکس ها</a>
        </div>
    </div>

    <!-- Page Content -->
    <div class="w3-padding-large" id="main">
        <!-- Header/Home -->
        <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
            <h1 class="w3-jumbo">
                {% if object.head_title %}
                {{ object.head_title }}
                {% else %}
                من عباس بوعذار هستم
                {% endif %}
            </h1>
            <p>
                {% if object.head_sub_title %}
                {{ object.head_sub_title }}
                {% else %}
                فوتبالیست و عکاس
                {% endif %}
            </p>
            <img src="   
                {% if object.head_image %}
                    {{ object.head_image.url }}
                {% else %}
                    {% static 'temp_type_two/man_smoke.jpg' %}
                {% endif %}" 
                alt="boy" class="w3-image" width="992" height="1108">
        </header>

        <!-- About Section -->
        <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
            <h2 class="w3-text-light-grey" style="direction: rtl;">
                {% if object.about_me_title %}
                {{ object.about_me_title }}
                {% else %}
                کسی که اسمش نه د داره نه ح داره
                {% endif %}
            </h2>
            <hr style="width:200px; margin-left: 80%;" class="w3-opacity">

            <p style="direction: rtl;">
                {% if object.about_me_description %}
                {{ object.about_me_description }}
                {% else %}
                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت
                چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه
                روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط
                فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود
                ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد
                گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد
                تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای
                علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد
                کرد. در این صورت می توان امید داشت که تمام و دشواری موجود
                در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان
                مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات
                پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.

                لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از
                صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله
                در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردها
                ی متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گ
                ذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شنا
                خت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان
                فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه
                راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای
                اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.

                {% endif %}


            </p>
            <h3 class="w3-padding-16 w3-text-light-grey" style="direction: rtl;">توانایی ها</h3>

            {% if object.ablility_1_title and object.ablility_1_precent %}
            <p>{{ object.ablility_1_title }}</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width: {{ object.ablility_1_precent }}%"></div>
            </div>
            {% else %}
            <p>داشتن یک ر در نام</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width:95%"></div>
            </div>
            {% endif %}

            {% if object.ablility_2_title and object.ablility_2_precent %}
            <p>{{ object.ablility_2_title }}</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width: {{ object.ablility_2_precent }}%"></div>
            </div>
            {% else %}
            <p>دیزاین وب</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width:85%"></div>
            </div>
            {% endif %}

            {% if object.ablility_3_title and object.ablility_3_precent %}
            <p>{{ object.ablility_3_title }}</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width: {{ object.ablility_3_precent }}%"></div>
            </div>
            {% else %}
            <p>فوتوشاپ</p>
            <div class="w3-white">
                <div class="w3-dark-grey" style="height:28px;width:80%"></div>
            </div>
            {% endif %}

            <br>

            <div class="flex-row-center w3-padding-16 w3-section w3-light-grey">
                {% if object.more_info_1_number and object.more_info_1_text %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">{{ object.more_info_1_number }}+</span>
                    {{ object.more_info_1_text }}
                </div>
                {% else %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">11+</span>
                    همکاران
                </div>
                {% endif %}

                {% if object.more_info_2_number and object.more_info_2_text %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">{{ object.more_info_2_number }}+</span>
                    {{ object.more_info_2_text }}
                </div>
                {% else %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">55+</span>
                    پروژه های انجام شده
                </div>
                {% endif %}

                {% if object.more_info_3_number and object.more_info_3_text %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">{{ object.more_info_3_number }}+</span>
                    {{ object.more_info_3_text }}
                </div>
                {% else %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">89+</span>
                    مشتری های راضی
                </div>
                {% endif %}

                {% if object.more_info_4_number and object.more_info_4_text %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">{{ object.more_info_4_number }}+</span>
                    {{ object.more_info_4_text }}
                </div>
                {% else %}
                <div class="w3-quarter flex-column-center w3-section">
                    <span class="w3-xlarge">85+</span>
                    ارتباط نداشتن با محمدی نامی
                </div>
                {% endif %}

            </div>
        </div>
    </div>

    <!-- Portfolio Section -->
    <div class="w3-padding-64 w3-content" id="photos">
        <h2 class="w3-text-light-grey" style="direction: rtl;">عکس ها</h2>
        <hr style="width:200px; margin-left: 80%;" class="w3-opacity">

        <!-- Grid for photos -->
        <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half">
                
                <img src="
                {% if object.img_1 %}
                {{ object.img_1.url }}
                {% else %}
                {% static 'temp_type_two/wedding.jpg' %}
                {% endif %}" style="width:100%">
                

                
                <img src="
                {% if object.img_2 %}
                {{ object.img_2.url }}
                {% else %}
                {% static 'temp_type_two/rocks.jpg' %}
                {% endif %}" style="width:100%">
                

                
                <img src="{% if object.img_3 %}
                {{ object.img_3.url }}
                {% else %}
                {% static 'temp_type_two/sailboat.jpg' %}
                {% endif %}" style="width:100%">
                
                <img src="{% if object.img_3 %}
                {{ object.img_4.url }}
                {% endif %}" style="width:100%">
            </div>

            <div class="w3-half">
               
                <img src=" 
                {% if object.img_5 %}
                {{ object.img_5.url }}
                {% else %}
                {% static 'temp_type_two/underwater.jpg' %}
                {% endif %}" style="width:100%">
                

                
                <img src="
                {% if object.img_6 %}
                {{ object.img_6.url }}
                {% else %}
                {% static 'temp_type_two/chef.jpg' %}
                {% endif %}" style="width:100%">
                

                
                <img src="
                {% if object.img_7 %}
                {{ object.img_7.url }}
                {% else %}
                {% static 'temp_type_two/wedding.jpg' %}
                {% endif %}
                " style="width:100%">
                
                
                <img src="{% if object.img_8 %}
                {{ object.img_8.url }}
                {% else%}
                {% static 'temp_type_two/p6.jpg' %}
                {% endif %}" style="width:100%">
                
            </div>
            <!-- End photo grid -->
        </div>
        <!-- End Portfolio Section -->
    </div>
    <!-- END PAGE CONTENT -->
    </div>
</body>

</html>

templates/temps/temps_list.html
{% extends "profile_base.html" %}
{% load static %}


{% block active_templates %}sidebar-btn-active{% endblock %}

{% block profile_content %}
<div class="container-fluid header-container">
    <div class="row">
        <div class="col-md-4">
            <div class="header center-column">
                <img src="
                {% if user.avatar %}
                {{ user.avatar.url }}
                {% else %}
                {% static 'images/profile.png'%}
                {% endif %}
                " class="profile">
                <div>{{ user.username }}</div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="header h-100">
                <div class="container-fluid h-100">
                    <div class="row h-100">
                        <div class="col-lg-9 center h-100">
                            <div class="h-50">
                                <p class="header-large-txt text-right" dir="rtl">
                                    صفحه انتخاب قالب پورتفولیتو</p>
                                <p class="header-small-txt text-right" dir="rtl">
                                    با چند کلیک ساده پورتفولیوی خودت رو بساز</p>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <img class="header-svg" src="{% static 'images/sapiens.svg'%}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <p class="text-right margin-template " dir="rtl">انتخاب قالب</p>
    <div class="center-row">

        {% for obj in object_list %}
        <a href="{% url 'products:activate_tempalte' obj.name %}">
            <div class="card card-style" style="
                    background-image: url('{{obj.image.url}}');
                ">
                {% if user.active_template == obj %}
                <div class="active-card center">
                    <div class="active-card-circle"></div>
                </div>
                {% endif %}
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/template.css' %}" type='text/css'>
{% endblock %}