ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import home_page, about_page, contact_page, login_page, register_page,logout_request,forget_password,send_email_done,change_password,change_password_done
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_page, name='login'),
    path('about-us', about_page),
    path('contact-us', contact_page),
    path('register', register_page, name='register'),
    path('logout/', logout_request, name='logout'),
    path('templates/', include("products.urls")),
    path('forget-password/',forget_password),
    path('forget-password/send-email-sucessfull/',send_email_done,name='send-email-sucessfull'),
    path('change-password/',change_password,name='change_password'),
    path('change-password/change-password-sucessfull/',change_password_done,name='change-password-sucessfull'),
    
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views

app_name = 'products' 
urlpatterns = [
    path('', views.TemplateListView.as_view(), name='template'),
    path('setting/', views.setting_page, name='setting'),
    path('show/<str:username>/', views.show_template, name='show'),
    path('activate_tempalte/<str:temp_name>/', views.activate_template, name='activate_tempalte'),

]

templates/about_page.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
        {{ title }}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/main.css" %}"/>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="bdcolor">

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="zahra text-center">

                {{ content }}

                </h1>
            <h3 class="zahra2 text-center">
                <br><br>
                گروه پلنگ مازندران فعالیت خود را از  شروع ترم 2 آغاز نموده و به امید حق علیه باطل هنوز ادامه دارد.<br>
                اعضای این گروه به شرح زیر میباشد:<br>
                امیرحسین بیدار - زهرا صفدری- مهدی قاسمی-هادی اتفاق<br>
            </h3>
            <h2 class="text-center">
                به امید موفقیت در این پروژه
            </h2>
            <hr><img class="zahra4" src="{% static "images/palang.jpg" %}" alt="static images" width="600" height="500">
        </div>
    </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href='https://cdn.fontcdn.ir/Font/Persian/Samim/Samim.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    {% block css %}{% endblock %}
</head>

<body class="structure">
    {% block content %}
        {#  render html files  #}
    {% endblock %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>

</html>

templates/profile_base.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="sidebar-margin">
    <!-- HEADBAR -->
    <div class="container-fluid border-bottom headbar">
        <div class="row">
            <div class="col-md-6">
                <p class="top-font">{% now "jS F Y H:i" %}</p>
            </div>
            <div class="col-md-6">
                <p class="text-right top-font" dir="rtl">صفحه اصلی > قالب ها </p>
            </div>
        </div>
    </div>
    <div class="mobile-headbar center-row border-bottom">
        <div>
            <img src="{% static 'images/Group 6.svg' %}">
            <p class="moblie-headbar-name">پورتفولیتو</p>
            <img src="{% static 'images/menu.svg' %}" class="menu-img">
        </div>
    </div>
    <!-- END HEADBAR -->
    <!-- Main Content -->
    {% block profile_content %}{% endblock %}
    <!-- End Main Content -->
</main>


<!-- SIDE BAR -->
<main class="sidebar border-left">
    <div class="h-25 sidebar-center-column sidebar-top">
        <img src="{% static 'images/Group 6.svg' %}" alt="">
        <div class='sidebar-head-txt'> پورتفولیتو </div>
    </div>
    <div class="h-75 sidebar-center-column">
        <a href="{% url 'products:template' %}" class="simple">
            <div class='sidebar-btn {% block active_templates %}{% endblock %}'>
                <span> قالب ها</span>
                <img src="{% static 'images/Ticket.svg' %}" alt="">
            </div>
        </a>

        <a href="{% url 'products:setting' %}" class="simple">
            <div class='sidebar-btn {% block active_setting%}{% endblock %}'>
                <span> تنظیمات</span>
                <img src="{% static 'images/Setting.svg' %}" alt="">
            </div>
        </a>

        <a href="{% url 'logout' %}" class="simple">
            <div class='sidebar-btn'>
                <span>خروج </span>
                <img src="{% static 'images/logout.svg' %}" alt="">
            </div>
        </a>
        {% if user.active_template %}
        <a href="{% url 'products:show' user.username %}" class="simple">
            <div class='sidebar-btn '>
                <span> نمایش </span>
                <img src="{% static 'images/Ticket Star.svg' %}" alt="">
            </div>
        </a>
        {% endif %}
    </div>
</main>
<!-- SIDE BAR END -->
{% endblock %} {% block js %}
<script>
    $('.menu-img').on('click', function() {
        $('.sidebar').animate({
            'width': 'toggle'
        });
    });
</script>
{% endblock %}